name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace 'main' with your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js (for any web bundling or npm commands, optional)
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Adjust the Node.js version if needed

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # If your `index.html` is in the root directory
